Allow anyone to submit a verification result (#148)
* Allow anyone to submit a verification result

* Change INVALID_CREDENTIAL_SCHEMA error

For some reason, this specific string was causing a Bytecode error in
the openzeppelin contract during an upgrade test:

```
  Error: Bytecode is not a valid hex string
  at hashBytecode (node_modules/@openzeppelin/upgrades-core/src/version.ts:31:11)
  at hashBytecodeWithoutMetadata (node_modules/@openzeppelin/upgrades-core/src/version.ts:47:10)
  at getVersion (node_modules/@openzeppelin/upgrades-core/src/version.ts:14:24)
  at getUnlinkedBytecode (node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:130:33)
  at getDeployData (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:48:47)
  at async deployProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:72:22)
  at async Proxy.upgradeProxy (node_modules/@openzeppelin/hardhat-upgrades/src/upgrade-proxy.ts:25:32)
at async Context.<anonymous> (test/permissioned/PoolAdminAccessControl.test.ts:178:7)
  ```